//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ObjectLoacator.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_HELP_DLG                    100
#define IDS_ABOUTBOX                    101
#define IDD_OBJECTLOACATOR_DIALOG       102
#define IDD_LIGHTDLG                    107
#define IDR_MAINFRAME                   128
#define IDD_VIEW_DLG                    136
#define IDD_MAIN_DLG                    140
#define IDD_GRIDCON                     141
#define IDR_MAIN_MENU                   142
#define IDD_CMD                         143
#define IDD_CHAR_SETTING                152
#define IDD_COLLIDER_CONTROLLER         154
#define IDD_WAVE_DLG                    164
#define IDC_BTN_SAVE                    1002
#define IDC_OBJLIST                     1003
#define IDC_LOGBOX                      1003
#define IDC_POS_X                       1004
#define IDC_POS_Y                       1005
#define IDC_POS_Z                       1006
#define IDC_ROT_X                       1007
#define IDC_ROT_Y                       1008
#define IDC_ROT_Z                       1009
#define IDC_SCALE_X                     1010
#define IDC_SCALE_Y                     1011
#define IDC_SCALE_Z                     1012
#define IDC_BTN_OBJEDIT                 1013
#define IDC_BTN_OBJDEL                  1014
#define IDC_MODELLIST                   1015
#define IDC_MATLIST                     1016
#define IDC_BTN_OBJCREATE               1017
#define IDC_BTN_LOAD                    1018
#define IDC_MODEL_INDEX                 1018
#define IDC_MOVE_OFFSET                 1019
#define IDC_OFFSET_CAPTION              1020
#define IDC_OBJECT_NAME                 1021
#define IDC_STATIC_NAME                 1022
#define IDC_FILE_NAME                   1023
#define IDC_STATIC_TYPE                 1023
#define IDC_LOG                         1024
#define IDC_STATIC_STRENGTH             1024
#define IDC_STATIC_FALLOFFSTART         1025
#define IDC_MAT_INDEX                   1026
#define IDC_STATIC_DIRECTION            1026
#define IDC_STATIC_MODEL_INDEX          1027
#define IDC_STATIC_FALLOFFEND           1027
#define IDC_STATIC_MODEL_INDEX2         1028
#define IDC_STATIC_POSITION             1028
#define IDC_MODEL_NAME                  1029
#define IDC_STATIC_SPOTPOWER            1029
#define IDC_MAT_NAME                    1030
#define IDC_MAP_WIDTH                   1034
#define IDC_MAP_HEIGHT                  1035
#define IDC_EDIT_MAP_WIDTH              1036
#define IDC_EDIT_MAP_HEIGHT             1037
#define IDC_EDIT_MAP_OFFSET             1038
#define IDC_MAP_OFFSET                  1039
#define IDC_TREE_CHAR                   1040
#define IDC_CHAR_NAME                   1041
#define IDC_CHAR_MODEL                  1042
#define IDC_CHAR_MATERIAL               1043
#define IDC_EDIT_CHAR_NAME              1044
#define IDC_EDIT_CHAR_MODEL             1045
#define IDC_EDIT_CHAR_MATERIAL          1046
#define IDC_LIST_MODEL                  1047
#define IDC_CHAR_MIN                    1048
#define IDC_CMD_LINE                    1048
#define IDC_CHAR_JI                     1049
#define IDC_CHAR_STAT                   1050
#define IDC_EDIT_CHAR_GONG              1051
#define IDC_EDIT_CHAR_MIN               1052
#define IDC_EDIT_CHAR_JI                1053
#define IDC_LIST_MATERIAL               1054
#define IDC_MODEL_LIST                  1055
#define IDC_MATERIAL_LIST               1056
#define IDC_CHAR_GONG                   1057
#define IDC_CHAR_HP                     1058
#define IDC_CHAR_MP                     1059
#define IDC_CHAR_SPEED                  1060
#define IDC_CHAR_ATTACK                 1061
#define IDC_CHAR_ATKSPD                 1062
#define IDC_CHAR_MAGIC                  1063
#define IDC_CHAR_DEF                    1064
#define IDC_CHAR_LUCK                   1065
#define IDC_EDIT_CHAR_LUCK              1066
#define IDC_EDIT_HP                     1067
#define IDC_EDIT_MP                     1068
#define IDC_EDIT_DEF                    1069
#define IDC_EDIT_SPEED                  1070
#define IDC_EDIT_ATTACK                 1071
#define IDC_EDIT_ATK_SPD                1072
#define IDC_EDIT_MAGIC                  1073
#define IDC_CHAR_CREATE                 1074
#define IDC_CHAR_DELETE                 1075
#define IDC_EDIT_CHAR_INDEX             1076
#define IDC_EDIT_CHAR_MODEL_INDEX       1077
#define IDC_EDIT_CHAR_MAT_INDEX         1078
#define IDC_COLLIDER_LISTBOX            1079
#define IDC_COLLIDER_ROT                1080
#define IDC_COLLIDER_POS                1081
#define IDC_COLLIDER_SCALE              1082
#define IDC_EDIT_COLLIDER_POSX          1083
#define IDC_EDIT_COLLIDER_POSY          1084
#define IDC_EDIT_COLLIDER_POSZ          1085
#define IDC_EDIT_COLLIDER_ROTX          1086
#define IDC_EDIT_COLLIDER_ROTY          1087
#define IDC_EDIT_COLLIDER_ROTZ          1088
#define IDC_EDIT_COLLIDER_SCALEX        1089
#define IDC_EDIT_COLLIDER_SCALEY        1090
#define IDC_EDIT_COLLIDER_SCALEZ        1091
#define IDC_CHECK_VISIBLE               1092
#define ID_CREATE_COLLIDER              1093
#define ID_DELETE_COLLIDER              1094
#define ID_EDIT_COLLIDER                1095
#define IDC_COMBO_OBJTYPE               1096
#define IDC_COMBO_REGEN_COL_INDEX       1097
#define IDC_BUTTON_EDIT_MAT_SELECTED    1102
#define IDC_BUTTON_EDIT_SCALE_SELECTED  1103
#define IDC_LIST_LIGHT                  1155
#define IDC_EDIT_LIGHT_NAME             1156
#define IDC_EDIT_STRENGTH_X             1157
#define IDC_EDIT_STRENGTH_Y             1158
#define IDC_EDIT_STRENGTH_Z             1159
#define IDC_EDIT_FALLOFFSTART           1160
#define IDC_EDIT_DIRECTION_X            1161
#define IDC_EDIT_DIRECTION_Y            1162
#define IDC_EDIT_DIRECTION_Z            1163
#define IDC_EDIT_FALLOFFEND             1164
#define IDC_EDIT_POSITION_X             1165
#define IDC_EDIT_POSITION_Y             1166
#define IDC_EDIT_POSITION_Z             1167
#define IDC_EDIT_SPOTPOWER              1168
#define IDC_BUTTON_CREATE               1169
#define IDC_BUTTON_EDIT                 1170
#define IDC_BUTTON_DELETE               1171
#define IDC_COMBO_LIGHT_TYPE            1172
#define IDC_STATIC_LIGHT_INFO           1174
#define IDC_COMBO_COL_TYPE              1177
#define IDC_EDIT_COLLIDER_INDEX         1178
#define IDC_WAVE_CREATE                 1179
#define IDC_WAVE_EDIT                   1180
#define IDC_WAVE_DELETE                 1181
#define IDC_EDIT_WAVE_ROW               1182
#define IDC_EDIT_WAVE_COL               1183
#define IDC_EDIT_WAVE_DX                1184
#define IDC_EDIT_WAVE_SPEED             1185
#define IDC_EDIT_WAVE_DAMPING           1186
#define IDC_WAVE_LIST                   1187
#define IDC_WAVE_ROW                    1188
#define IDC_WAVE_COL                    1189
#define IDC_WAVE_DX                     1190
#define IDC_WAVE_SPEED                  1191
#define IDC_EDIT_WAVE_POSX              1192
#define IDC_EDIT_WAVE_POSY              1193
#define IDC_EDIT_WAVE_POSZ              1194
#define IDC_EDIT_WAVE_ROTX              1195
#define IDC_EDIT_WAVE_ROTY              1196
#define IDC_EDIT_WAVE_ROTZ              1197
#define IDC_EDIT_WAVE_SCALEX            1198
#define IDC_EDIT_WAVE_SCALEY            1199
#define IDC_EDIT_WAVE_SCALEZ            1200
#define IDC_WAVE_POS                    1201
#define IDC_WAVE_ROT                    1202
#define IDC_WAVE_SCALE                  1203
#define ID_MAIN_VIEWER                  32777
#define ID_MAIN_OBJLOCATOR              32778
#define ID_MAIN_GRIDCON                 32779
#define ID_SAVE                         32780
#define ID_LOAD                         32781
#define ID_EXIT                         32782
#define ID_MAIN_CMD                     32783
#define ID_MAIN_CHAR_EIDT               32784
#define ID_LOAD_FBX                     32791
#define ID_MENU_SAVE                    32792
#define ID_MENU_LOAD                    32793
#define ID_MENU_LOAD_FBX                32794
#define ID_MENU_EXIT                    32795
#define ID_COLLIDER_WINDOW              32796
#define ID_LIGHT_WINDOW                 32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1185
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
